### ISSUE TITLE
Versions after 3.2.2

### ISSUE THREAD

**Issue by oozusta** [broccolijs/broccoli-concat#127]
I am using ember-cli and thus whenever I do a fresh install of packages I get the new version. I don't have the option of locking back to 3.2.2 without locking every one of my packages - shouldn't the minor versions be non-breaking?

**Comment by stefanpenner** [comment]
What issue are you seeing?

**Comment by jeanduplessis** [comment]
@stefanpenner might relate to this issue: https://github.com/ef4/fast-sourcemap-concat/issues/53

**Comment by stefanpenner** [comment]
@jeanduplessis I'll assume it is.
@oozusta if I was mistaken, please provide additional details and I can gladly reopen.
