### ISSUE TITLE
Fails if `outputFile` specifies a non-existing directory

### ISSUE THREAD

**Issue by kevinansfield** [broccolijs/broccoli-concat#149]
After upgrading to 4.2.1 our ember builds started failing (at least on macOS).

```
>> (node:52291) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T/broccoli-52291zjOJHNK9FLVI/out-541-simple_concat_concat/assets/codemirror/codemirror.js'
>>     at Object.openSync (fs.js:443:3)
>>     at Object.writeFileSync (fs.js:1194:35)
>>     at Object.handleFs (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-concat/node_modules/broccoli-output-wrapper/dist/index.js:45:44)
>>     at Concat._doPatchBasedBuild (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-concat/concat.js:166:17)
>>     at Concat.build (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-concat/concat.js:104:19)
>>     at resolve (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli/dist/wrappers/transform-node.js:68:45)
>>     at new Promise (<anonymous>)
>>     at TransformNodeWrapper.build (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli/dist/wrappers/transform-node.js:53:16)
>>     at Promise.resolve.then.then.then (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli/dist/builder.js:99:36)
>>     at process._tickCallback (internal/process/next_tick.js:68:7)
```

The relevant part of our `ember-cli-build.js` [where we use `broccoli-concat`](https://github.com/TryGhost/Ghost-Admin/blob/master/ember-cli-build.js#L45-L50) is as follows:

```
let jsTree = concat(tree, {
    outputFile: 'assets/codemirror/codemirror.js',
    headerFiles: ['lib/codemirror.js'],
    inputFiles: ['mode/**/*'],
    sourceMapConfig: {enabled: false}
});
```

Changing the `outputFile` to remove the directory allows that step of the build to pass. Downgrading to 4.0.0 and keeping the directory in `outputFile` also allows works fine.

**Comment by bendemboski** [comment]
[This](https://github.com/broccolijs/broccoli-concat/commit/4bce6c4481232f12f2c30a51a5809142b6fe4c96#diff-e921366d154601ee09e020742b81dd9fL166-R164) is the culprit -- changing from `fs-extra`'s `outputFileSync` which creates missing directories to wherever that `writeFileSync` points, which apparently does not.

**Comment by rwjblue** [comment]
@SparshithNR - Can you look into this? I think we'll need to make some changes in `broccoli-output-wrapper` to accommodate...

**Comment by SparshithNR** [comment]
@rwjblue https://github.com/SparshithNR/broccoli-output-wrapper/pull/10

**Comment by kevinansfield** [comment]
Closing as this appears to have been resolved. Thanks! 😄
